# Generated by Django 4.1.7 on 2023-03-08 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightservice',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='foodservice',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='locations',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='travelservice',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='departure',
            field=models.DateTimeField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='users',
            name='phoneNumber',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='returndate',
            field=models.DateTimeField(default=datetime.date),
        ),
    ]
