# Generated by Django 4.1.7 on 2023-03-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_flightservice_image_foodservice_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightservice',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='foodservice',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
