# Generated by Django 4.1.7 on 2023-03-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_flightservice_image_alter_foodservice_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
