# Generated by Django 4.1.7 on 2023-03-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_rename_locations_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='static/images/')),
            ],
        ),
    ]
