# Generated by Django 4.1.7 on 2023-03-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_services_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
    ]
