# Generated by Django 4.1.7 on 2023-03-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_services_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
